# Dockerfile for use with Toolbox

FROM registry.endlessm-sf.com/eos-toolbox:master

# Install the dependencies for the build system
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y \
        build-essential \
        libffi-dev \
        libssl-dev \
        ccache \
        openjdk-11-jdk-headless \
        python-is-python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        qemu-system-gui \
        qemu-system-x86 \
        qemu-utils \
        wget \
        && \
    apt-get clean

# Install Android SDK
ENV ANDROID_HOME=/opt/android
ENV ANDROIDSDK=$ANDROID_HOME/sdk
ENV ANDROIDNDK=$ANDROIDSDK/ndk-bundle
COPY Makefile /tmp/
RUN make -C /tmp setup SDK=$ANDROIDSDK && \
  rm -f /tmp/Makefile

# Put some of the SDK tools in PATH
ENV PATH="${PATH}:${ANDROIDSDK}/cmdline-tools/latest/bin:${ANDROIDSDK}/platform-tools"
